# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenAPIPetstore.Model.Order do
  @moduledoc """
  An order for a pets from the pet store
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"petId",
    :"quantity",
    :"shipDate",
    :"status",
    :"complete"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"petId" => integer() | nil,
    :"quantity" => integer() | nil,
    :"shipDate" => DateTime.t | nil,
    :"status" => String.t | nil,
    :"complete" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: OpenAPIPetstore.Model.Order do
  def decode(value, _options) do
    value
  end
end

